name: Check Jira tickets in Github
on:
  workflow_dispatch:
    inputs:
      initial_date:
        description: The initial date to check for the commits
        required: true
      final_date:
        description: The final date to check for commits
        required: true

env:
  REPO: ${{github.repository}}
  BRANCH_NAME: main
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  START_DATE: ${{github.event.inputs.initial_date}}
  END_DATE: ${{github.event.inputs.final_date}}
  JIRA_URL: "wwww"
  JIRA_USERNAME: "www"
  JIRA_TOKEN: "www"


jobs:
  jira_tickets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jira requests
    - name: Extract tickets and check status on Jira
      run: |
        python github_jira_integration.py --Repo=${{env.REPO}} --Branch_name=${{env.BRANCH_NAME}} --Github_token=${{env.GITHUB_TOKEN}} --Start_date=${{env.START_DATE}} --End_date=${{env.END_DATE}} --Jira_url=${{env.JIRA_URL}} --Jira_username=${{env.JIRA_USERNAME}} --Jira_token=${{env.JIRA_TOKEN}}